# NOTE: Generated By HttpRunner v3.1.6
# FROM: api/login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("登录测试")

    teststeps = [
        Step(
            RunRequest("登录测试")
            .with_variables(**{"username": "keyou1", "password": 123456})
            .post("/user/login/")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "$username", "password": "$password"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
