# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/login.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from api.login_test import TestCaseLogin as Login


class TestCaseLogin(HttpRunner):

    config = Config("登录接口列表").base_url("http://api.keyou.site:8000")

    teststeps = [
        Step(
            RunTestCase("$title")
            .call(Login)
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("body", "$contain_msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
